# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VOAPBxHos2vXL_vNZZZF9JUfy4Izjeb
"""

import gradio as gr
import os
import json
from ocr_helper import extract_text_from_image
from chatbot import continuous_chat_with_basic_chatbot, continuous_chat_with_llama
from user_profile import create_or_update_profile, load_user_profiles

# Main function to handle Gradio interface
def main_menu(user_id, image, update_profile=False, dietary_restrictions=None, preferences=None):
    # Extract text from uploaded image
    extracted_text = extract_text_from_image(image)

    # Load or update the user's profile
    if update_profile:
        create_or_update_profile(user_id, dietary_restrictions, preferences)

    # Options to select chatbot
    chat_option = input("Choose a chatbot option: (1) Ingredients Assistant (2) Shopping Assistant")
    if chat_option == "1":
        return continuous_chat_with_basic_chatbot(extracted_text)
    elif chat_option == "2":
        return continuous_chat_with_llama(extracted_text)
    else:
        return "Invalid choice."

# Gradio interface
with gr.Blocks() as interface:
    user_id = gr.Textbox(label="User ID")
    image_input = gr.Image(label="Upload Image")
    update_profile = gr.Checkbox(label="Update Profile?")
    dietary_restrictions = gr.Textbox(label="Dietary Restrictions (comma-separated)", visible=False)
    preferences = gr.Textbox(label="Preferences (comma-separated)", visible=False)

    submit = gr.Button("Submit")

    submit.click(main_menu, inputs=[user_id, image_input, update_profile, dietary_restrictions, preferences], outputs="text")

# Launch the app on Hugging Face Spaces
interface.launch()